filebeat.inputs:
  - type: filestream
    id: wazuh-alerts
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    parsers:
      - ndjson:
          keys_under_root: true
          overwrite_keys: true
          add_error_key: true
          expand_keys: true
    fields:
      log_source: wazuh
    fields_under_root: true
    prospector.scanner.check_interval: 5s

  - type: syslog
    format: rfc3164
    enabled: true
    protocol.udp:
      host: "0.0.0.0:5514"
    fields:
      log_source: metasploitable
      host_role: vuln-linux
    fields_under_root: true

setup.template.enabled: false
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]
  ssl.verification_mode: full
  index: "wazuh-alerts-4.x-%{+yyyy.MM.dd}"
  allow_older_versions: true
  action: "index"

logging.level: info
logging.to_stderr: true
logging.to_files: false
