%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[172.18.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"

default-log-dir: /var/log/suricata/

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes
  - eve-log:
      enabled: yes
      filename: eve.json
      rotate-interval: day
      pcap-file: false
      community-id: true
      types:
        - alert:
            payload: yes
            payload-printable: yes
            packet: yes
            metadata: yes
        - dns:
            query: yes
            answer: yes
        - http:
            extended: yes
        - tls:
            extended: yes
        - ssh
        - flow
        - stats:
            totals: yes
            threads: no

af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    ring-size: 200000

detect:
  profile: medium
  custom-values:
    toclient-groups: 3
    toserver-groups: 25
  sgh-mpm-context: auto

threading:
  set-cpu-affinity: no
  detect-thread-ratio: 1.0

app-layer:
  protocols:
    http:
      enabled: yes
    dns:
      enabled: yes
    tls:
      enabled: yes
    ssh:
      enabled: yes
    ftp:
      enabled: yes

rule-files:
  - /etc/suricata/rules/local.rules
  - /etc/suricata/rules/rules/emerging-malware.rules
  - /etc/suricata/rules/rules/emerging-exploit.rules
  - /etc/suricata/rules/rules/emerging-exploit_kit.rules
  - /etc/suricata/rules/rules/emerging-scan.rules
  - /etc/suricata/rules/rules/emerging-web_server.rules
  - /etc/suricata/rules/rules/emerging-web_specific_apps.rules
  - /etc/suricata/rules/rules/emerging-sql.rules
  - /etc/suricata/rules/rules/emerging-dns.rules
  - /etc/suricata/rules/rules/emerging-ftp.rules
  - /etc/suricata/rules/rules/emerging-shellcode.rules
  - /etc/suricata/rules/rules/emerging-policy.rules
  - /etc/suricata/rules/rules/tor.rules
  - /etc/suricata/rules/rules/botcc.rules
  - /etc/suricata/rules/rules/compromised.rules
  - /etc/suricata/rules/rules/threatview_CS_c2.rules

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config
threshold-file: /etc/suricata/threshold.conf
