# Suppress internal SOC traffic noise
suppress gen_id 1, sig_id 2221034, track by_src, ip 172.18.0.0/16
suppress gen_id 1, sig_id 1000011, track by_src, ip 172.18.0.0/16
suppress gen_id 1, sig_id 1000016, track by_src, ip 172.18.0.0/16
