version: '3.8'

services:
  victim-windows:
    image: soc-stack-victim-windows:latest
    container_name: victim-windows
    networks:
      - soc-net
    restart: unless-stopped

  victim-ubuntu:
    image: soc-stack-victim-ubuntu
    container_name: victim-ubuntu
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "2222:22"
      - "8888:80"
      - "2121:21"

  victim-metasploitable:
    image: tleemcjr/metasploitable2
    container_name: victim-metasploitable
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "2223:22"
      - "8889:80"
      - "2122:21"

  victim-dvwa:
    image: victim-dvwa-img:latest
    container_name: victim-dvwa
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "8890:80"

  victim-jenkins:
    image: soc-stack-victim-jenkins
    container_name: victim-jenkins
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "9090:8080"

  victim-ftp:
    image: soc-stack-victim-ftp
    container_name: victim-ftp
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "2124:21"
      - "21100-21110:21100-21110"

  victim-dns:
    image: soc-stack-victim-dns
    container_name: victim-dns
    networks:
      - soc-net
    restart: unless-stopped

  victim-database:
    image: soc-stack-victim-database
    container_name: victim-database
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "3306:3306"

  victim-mail:
    image: soc-stack-victim-mail
    container_name: victim-mail
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "2525:25"
      - "1143:143"

  victim-iot:
    image: soc-stack-victim-iot
    container_name: victim-iot
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8891:8080"

  victim-webapi:
    image: raesene/bwapp
    container_name: victim-webapi
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "8892:80"

  kali-attacker:
    build:
      context: ./lab/kali-attacker
      dockerfile: Dockerfile
    image: kali-attacker-persistent:latest
    container_name: kali-attacker
    hostname: kali-attacker
    command: bash -c 'tail -f /dev/null'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      soc-net:

  fleet-server:
    image: docker.elastic.co/elastic-agent/elastic-agent:8.13.0
    container_name: fleet-server
    networks:
      - soc-net
    restart: unless-stopped
    ports:
      - "8220:8220"

networks:
  soc-net:
    external: true
    name: soc-stack_soc-net
