name: soc-stack
networks:
  soc-net:
    driver: bridge
    name: soc-stack_soc-net
services:
  connector-misp:
    container_name: connector-misp
    depends_on:
      misp:
        condition: service_healthy
        required: true
      opencti:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '268435456'
    environment:
      CONNECTOR_CONFIDENCE_LEVEL: '75'
      CONNECTOR_ID: misp-connector-001
      CONNECTOR_LOG_LEVEL: error
      CONNECTOR_NAME: MISP
      CONNECTOR_SCOPE: misp-galaxy,misp-attribute
      CONNECTOR_TYPE: EXTERNAL_IMPORT
      MISP_CREATE_INDICATORS: 'true'
      MISP_CREATE_OBSERVABLES: 'true'
      MISP_CREATE_REPORTS: 'true'
      MISP_DATETIME_ATTRIBUTE: timestamp
      MISP_FEED_MODE: 'false'
      MISP_IMPORT_FROM_DATE: '2026-01-01'
      MISP_INTERVAL: '60'
      MISP_KEY: e998ec66e5bb63da708e88ddc53679317991d93b
      MISP_REPORT_TYPE: misp-event
      MISP_SSL: 'false'
      MISP_URL: http://misp
      OPENCTI_TOKEN: bbfe1ad3-c317-4efe-9f14-0ea298a9476d
      OPENCTI_URL: http://opencti:8080
    image: opencti/connector-misp:6.0.5
    networks:
      soc-net: null
    restart: unless-stopped
  connector-mitre:
    container_name: connector-mitre
    depends_on:
      opencti:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '134217728'
    environment:
      CONNECTOR_CONFIDENCE_LEVEL: '15'
      CONNECTOR_ID: 80468305-6490-449e-990a-1150493630f4
      CONNECTOR_NAME: MITRE_ATTACK
      CONNECTOR_SCOPE: identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      CONNECTOR_TYPE: EXTERNAL_IMPORT
      MITRE_INTERVAL: '7'
      OPENCTI_TOKEN: bbfe1ad3-c317-4efe-9f14-0ea298a9476d
      OPENCTI_URL: http://opencti:8080
    image: opencti/connector-mitre:6.0.5
    memswap_limit: '2147483648'
    networks:
      soc-net: null
    restart: unless-stopped
  elastalert:
    command:
    - 'printf ''%s\n'' ''rules_folder: /opt/elastalert/rules'' ''run_every:'' ''  minutes:
      1'' ''buffer_time:'' ''  minutes: 15'' ''es_host: elasticsearch'' ''es_port:
      9200'' ''es_username: elastic'' ''es_password: TMcoI=yr0ulMqTIzH++E'' ''writeback_index:
      elastalert_status'' ''alert_time_limit:'' ''  days: 2'' > /tmp/ea.yaml && exec
      elastalert --verbose --config /tmp/ea.yaml'
    container_name: elastalert
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: '134217728'
    dns:
    - 8.8.8.8
    entrypoint:
    - /bin/sh
    - -c
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PASSWORD: TMcoI=yr0ulMqTIzH++E
      ELASTICSEARCH_PORT: '9200'
      ELASTICSEARCH_USERNAME: elastic
      SLACK_WEBHOOK_URL: ''
    image: jertel/elastalert2:latest
    networks:
      soc-net: null
    restart: unless-stopped
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/elastalert-cfg
      target: /opt/elastalert-cfg
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/elastalert/rules
      target: /opt/elastalert/rules
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/elastalert/logs
      target: /opt/elastalert/logs
      type: bind
  elasticsearch:
    container_name: elasticsearch
    deploy:
      resources:
        limits:
          cpus: 2
          memory: '2621440000'
        reservations:
          memory: '1073741824'
    environment:
      ELASTIC_PASSWORD: TMcoI=yr0ulMqTIzH++E
      ES_JAVA_OPTS: -Xms1g -Xmx1500m
      discovery.type: single-node
      xpack.security.enabled: 'true'
      xpack.security.http.ssl.enabled: 'false'
    healthcheck:
      interval: 20s
      retries: 10
      start_period: 1m0s
      test:
      - CMD-SHELL
      - curl -sf -u elastic:TMcoI=yr0ulMqTIzH++E http://localhost:9200/_cluster/health
        | grep -vq '"status":"red"'
      timeout: 10s
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '9200'
      target: 9200
    restart: unless-stopped
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - source: es_data
      target: /usr/share/elasticsearch/data
      type: volume
      volume: {}
  elasticsearch-init:
    command:
    - /bin/bash
    - /init-es.sh
    container_name: elasticsearch-init
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    environment:
      ELASTIC_PASSWORD: TMcoI=yr0ulMqTIzH++E
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    networks:
      soc-net: null
    restart: 'no'
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /tmp/init-es.sh
      target: /init-es.sh
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/elasticsearch
      target: /output
      type: bind
  filebeat:
    command:
    - filebeat
    - -e
    - -strict.perms=false
    - -c
    - /filebeat-cfg/filebeat.yml
    container_name: filebeat
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: '134217728'
    image: docker.elastic.co/beats/filebeat:8.13.0
    networks:
      soc-net: null
    restart: unless-stopped
    user: root
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/filebeat-cfg
      target: /filebeat-cfg
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/wazuh/logs
      target: /var/ossec/logs
      type: bind
    - bind:
        create_host_path: true
      source: /var/log/filebeat
      target: /var/log/filebeat
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/suricata/logs
      target: /var/log/suricata
      type: bind
  kibana:
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: '1073741824'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYV90b2tlbl8xNzc3OTkzOTI1Ol9WQWtGM0h3U09hQUFfREJIMDFmZGc
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: b19cecf4b77672aeba86532c8f80b45e6b4bfe61d4a6427d0fc228700ae498eb
      XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_FLEET_AGENTS_FLEET_SERVER_HOSTS: '["http://fleet-server:8220"]'
      XPACK_REPORTING_ENCRYPTIONKEY: b19cecf4b77672aeba86532c8f80b45e6b4bfe61d4a6427d0fc228700ae498eb
      XPACK_SECURITY_ENCRYPTIONKEY: b19cecf4b77672aeba86532c8f80b45e6b4bfe61d4a6427d0fc228700ae498eb
    healthcheck:
      interval: 30s
      retries: 10
      start_period: 1m30s
      test:
      - CMD-SHELL
      - curl -sf http://localhost:5601/api/status | grep -q 'available' || curl -sf
        http://localhost:5601/api/status | grep -q 'degraded'
      timeout: 10s
    image: docker.elastic.co/kibana/kibana:8.13.0
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '5601'
      target: 5601
    restart: unless-stopped
  logstash:
    container_name: logstash
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '629145600'
    environment:
      ELASTIC_PASSWORD: TMcoI=yr0ulMqTIzH++E
      ELASTIC_USERNAME: elastic
      LOGSTASH_PIPELINE_WORKERS: '1'
      LS_JAVA_OPTS: -Xms256m -Xmx384m
      XPACK_MONITORING_ENABLED: 'false'
    image: docker.elastic.co/logstash/logstash:8.13.0
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '5000'
      target: 5000
    - mode: ingress
      protocol: udp
      published: '5001'
      target: 5001
    restart: unless-stopped
    user: root
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/logstash/pipeline
      target: /usr/share/logstash/pipeline
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/suricata/logs
      target: /var/log/suricata
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/logstash/geoip
      target: /usr/share/logstash/geoip
      type: bind
  memcached:
    container_name: memcached
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: '67108864'
    image: memcached:alpine
    networks:
      soc-net: null
    restart: unless-stopped
  minio:
    command:
    - server
    - /data
    container_name: minio
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '134217728'
    environment:
      MINIO_ROOT_PASSWORD: opencti_password
      MINIO_ROOT_USER: opencti
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
    image: minio/minio:latest
    networks:
      soc-net: null
    restart: unless-stopped
  misp:
    container_name: misp
    depends_on:
      misp-db:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '629145600'
    environment:
      BASE_URL: http://localhost:9001
      DISABLE_SSL_REDIRECT: 'true'
      ENABLE_REDIS_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: misp
      MYSQL_HOST: misp-db
      MYSQL_PASSWORD: misp_password
      MYSQL_USER: misp
      PHP_SESSION_COOKIE_SECURE: 'false'
      PHP_SESSION_DEFAULTS: redis
      REDIS_HOST: misp-redis
      REDIS_PASSWORD: ''
    healthcheck:
      interval: 30s
      retries: 10
      start_period: 5m0s
      test:
      - CMD
      - /bin/bash
      - /healthcheck.sh
      timeout: 10s
    image: ghcr.io/misp/misp-docker/misp-core:latest
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '9001'
      target: 80
    - mode: ingress
      protocol: tcp
      published: '9002'
      target: 443
    restart: unless-stopped
    volumes:
    - source: misp-app
      target: /var/www/MISP
      type: volume
      volume: {}
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/misp/healthcheck.sh
      target: /healthcheck.sh
      type: bind
  misp-db:
    container_name: misp-db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '734003200'
    environment:
      MYSQL_DATABASE: misp
      MYSQL_PASSWORD: misp_password
      MYSQL_ROOT_PASSWORD: misp_root_password
      MYSQL_USER: misp
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost -uroot -pmisp_root_password --silent
    image: mysql:8.0
    networks:
      soc-net: null
    restart: unless-stopped
    volumes:
    - source: misp-db-data
      target: /var/lib/mysql
      type: volume
      volume: {}
  misp-redis:
    container_name: misp-redis
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: '67108864'
    image: redis:7-alpine
    networks:
      soc-net: null
    restart: unless-stopped
  opencti:
    container_name: opencti
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
      minio:
        condition: service_healthy
        required: true
      rabbitmq:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: '1572864000'
    environment:
      APP__ADMIN__EMAIL: admin@opencti.io
      APP__ADMIN__PASSWORD: Admin@123!
      APP__ADMIN__TOKEN: bbfe1ad3-c317-4efe-9f14-0ea298a9476d
      APP__BASE_URL: http://localhost:3000
      APP__PORT: '8080'
      DATABASE__TYPE: elasticsearch
      ELASTICSEARCH__PASSWORD: TMcoI=yr0ulMqTIzH++E
      ELASTICSEARCH__SSL_VERIFY: 'false'
      ELASTICSEARCH__URL: http://elasticsearch:9200
      ELASTICSEARCH__USERNAME: elastic
      MINIO__ACCESS_KEY: opencti
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: opencti_password
      MINIO__USE_SSL: 'false'
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__PASSWORD: guest
      RABBITMQ__PORT: '5672'
      RABBITMQ__USER: guest
      REDIS__HOSTNAME: opencti-redis
      REDIS__PORT: '6379'
    healthcheck:
      interval: 30s
      retries: 15
      start_period: 2m0s
      test:
      - CMD-SHELL
      - wget -qO- http://localhost:8080/graphql > /dev/null 2>&1; [ $$? -le 1 ] &&
        exit 0 || exit 1
      timeout: 15s
    image: opencti/platform:6.0.5
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '3000'
      target: 8080
    restart: unless-stopped
  opencti-redis:
    command:
    - redis-server
    - --maxmemory
    - 96mb
    - --maxmemory-policy
    - allkeys-lru
    container_name: opencti-redis
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '134217728'
    image: redis:7-alpine
    networks:
      soc-net: null
    restart: unless-stopped
  opencti-worker:
    container_name: opencti-worker
    depends_on:
      opencti:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: '134217728'
    environment:
      MINIO__ACCESS_KEY: opencti
      MINIO__ENDPOINT: minio
      MINIO__PORT: '9000'
      MINIO__SECRET_KEY: opencti_password
      MINIO__USE_SSL: 'false'
      OPENCTI_TOKEN: bbfe1ad3-c317-4efe-9f14-0ea298a9476d
      OPENCTI_URL: http://opencti:8080
      RABBITMQ__HOSTNAME: rabbitmq
      RABBITMQ__PASSWORD: guest
      RABBITMQ__PORT: '5672'
      RABBITMQ__USER: guest
      WORKER_LOG_LEVEL: info
    image: opencti/worker:6.0.5
    networks:
      soc-net: null
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: '268435456'
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - CMD
      - rabbitmq-diagnostics
      - -q
      - ping
    image: rabbitmq:3.12-management-alpine
    networks:
      soc-net: null
    restart: unless-stopped
  suricata:
    cap_add:
    - NET_ADMIN
    - NET_RAW
    - SYS_NICE
    command:
    - -i
    - eth0
    - --set
    - default-rule-path=/var/lib/suricata/rules
    - -s
    - /var/lib/suricata/rules/suricata.rules
    container_name: suricata
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '134217728'
    image: jasonish/suricata:latest
    networks:
      soc-net: null
    restart: unless-stopped
    volumes:
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/suricata/rules
      target: /etc/suricata/rules
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/suricata/logs
      target: /var/log/suricata
      type: bind
  thehive:
    command:
    - --secret
    - SOCstack2026!TheHive
    - --no-cql-wait
    - --bdb-directory
    - /data/db
    - --index-backend
    - elasticsearch
    - --es-hostnames
    - elasticsearch
    - --es-username
    - elastic
    - --es-password
    - sYVfKJCe2RCfELjf=GLa
    - --no-config-cortex
    container_name: thehive
    depends_on:
      elasticsearch:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '629145600'
    environment:
      JVM_OPTS: -Xms256m -Xmx384m
    image: strangebee/thehive:5.2
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '9000'
      target: 9000
    restart: unless-stopped
    volumes:
    - source: thehive_data
      target: /data
      type: volume
      volume: {}
  vt-enricher:
    build:
      context: /home/said/soc-stack/threat-intelligence
      dockerfile: Dockerfile
    container_name: vt-enricher
    depends_on:
      elasticsearch:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: '134217728'
    environment:
      ES_HOST: http://elasticsearch:9200
      ES_PASS: TMcoI=yr0ulMqTIzH++E
      ES_PASSWORD: TMcoI=yr0ulMqTIzH++E
      ES_USER: elastic
      ES_USERNAME: elastic
      VIRUSTOTAL_API_KEY: ''
    image: vt-enricher:local
    networks:
      soc-net: null
    restart: unless-stopped
  wazuh-manager:
    container_name: wazuh-manager
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: '536870912'
    environment:
      API_PASSWORD: Wazuh1234!
      API_USERNAME: wazuh
      INDEXER_PASSWORD: TMcoI=yr0ulMqTIzH++E
      INDEXER_URL: http://elasticsearch:9200
      INDEXER_USERNAME: elastic
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 1m0s
      test:
      - CMD-SHELL
      - curl -sf -k -u wazuh:Wazuh1234! -X POST https://localhost:55000/security/user/authenticate
        | grep -q 'token'
      timeout: 10s
    image: wazuh/wazuh-manager:4.7.5
    init: true
    networks:
      soc-net: null
    ports:
    - mode: ingress
      protocol: tcp
      published: '1514'
      target: 1514
    - mode: ingress
      protocol: udp
      published: '1514'
      target: 1514
    - mode: ingress
      protocol: tcp
      published: '1515'
      target: 1515
    - mode: ingress
      protocol: tcp
      published: '55000'
      target: 55000
    restart: unless-stopped
    volumes:
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/wazuh/init-dirs.sh
      target: /init-dirs.sh
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/config/shared/default
      target: /var/ossec/etc/shared/default
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/lists
      target: /var/ossec/etc/lists
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/rules
      target: /var/ossec/etc/rules
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/decoders
      target: /var/ossec/etc/decoders
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/config/ossec.conf
      target: /var/ossec/etc/ossec.conf
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/logs
      target: /var/ossec/logs
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/set_wazuh_pass.py
      target: /tmp/set_wazuh_pass.py
      type: bind
    - bind:
        create_host_path: true
      read_only: true
      source: /home/said/soc-stack/wazuh/filebeat-template.yml
      target: /filebeat-template.yml
      type: bind
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/wazuh/filebeat-config
      target: /etc/filebeat
      type: bind
  yara-scanner:
    build:
      context: /home/said/soc-stack/yara/scanner
      dockerfile: Dockerfile
    command:
    - bash
    - -c
    - while true; do python3 /scanner/scan.py || echo "YARA scan failed, retrying...";
      sleep 10; done
    container_name: yara-scanner
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: '67108864'
    networks:
      soc-net: null
    restart: unless-stopped
    volumes:
    - bind:
        create_host_path: true
      source: /home/said/soc-stack/yara/samples
      target: /samples
      type: bind
    - read_only: true
      source: yara-dvwa
      target: /victims/dvwa
      type: volume
      volume: {}
    - read_only: true
      source: yara-ubuntu-www
      target: /victims/ubuntu-www
      type: volume
      volume: {}
    - read_only: true
      source: yara-ubuntu-tmp
      target: /victims/ubuntu-tmp
      type: volume
      volume: {}
    - read_only: true
      source: yara-ftp
      target: /victims/ftp
      type: volume
      volume: {}
volumes:
  es_data:
    name: soc-stack_es_data
  misp-app:
    name: soc-stack_misp-app
  misp-db-data:
    name: soc-stack_misp-db-data
  thehive_data:
    name: soc-stack_thehive_data
  yara-dvwa:
    external: true
    name: yara-dvwa
  yara-ftp:
    external: true
    name: yara-ftp
  yara-ubuntu-tmp:
    external: true
    name: yara-ubuntu-tmp
  yara-ubuntu-www:
    external: true
    name: yara-ubuntu-www
