server {
    listen 80;
    location / {
        proxy_pass https://misp:443;
        proxy_ssl_verify off;
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
