es_host: elasticsearch
es_port: 9200
writeback_index: elastalert_status
es_username: ${ELASTIC_USERNAME}
es_password: ${ELASTIC_PASSWORD}
buffer_time:
  minutes: 15
es_conn_timeout: 20
rules_folder: /opt/elastalert/rules
run_every:
  minutes: 1
alert_time_limit:
  minutes: 5
aggregation: {}
smtp_host: localhost
from_addr: alerts@localhost
reply_to: alerts@localhost
