[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:wazuh-agentd]
command=/var/ossec/bin/wazuh-agentd -f
autostart=true
autorestart=true
startsecs=5
startretries=10
stderr_logfile=/var/ossec/logs/agentd-stderr.log
stdout_logfile=/var/ossec/logs/agentd-stdout.log

[program:wazuh-logcollector]
command=/var/ossec/bin/wazuh-logcollector -f
autostart=true
autorestart=true
startsecs=5
startretries=5
stderr_logfile=/var/ossec/logs/logcollector-stderr.log
stdout_logfile=/var/ossec/logs/logcollector-stdout.log
