rules_folder: /opt/elastalert/rules
run_every:
  minutes: 1
buffer_time:
  minutes: 60
max_instances: 3
es_host: elasticsearch
es_port: 9200
es_username: "elastic"
es_password: "SOCstack2026!"
writeback_index: elastalert_status

# SMTP Configuration
smtp_host: smtp.gmail.com
smtp_port: 465
smtp_ssl: true
smtp_starttls: false
from_addr: "garnitsaid01@gmail.com"
smtp_auth_file: "/opt/elastalert/smtp_auth.yaml"
email_reply_to: "garnitsaid01@gmail.com"

# Other global settings
alert_time_limit:
  days: 2
silence_cache_duration:
  hours: 1
old_query_limit:
  weeks: 1
