# Suppress C2 and PowerShell false positives from internal SOC components
suppress gen_id 1, sig_id 1000011, track by_src, ip 172.18.0.6
suppress gen_id 1, sig_id 1000011, track by_src, ip 172.18.0.8
suppress gen_id 1, sig_id 1000011, track by_src, ip 172.18.0.9
suppress gen_id 1, sig_id 1000011, track by_src, ip 172.18.0.19
suppress gen_id 1, sig_id 1000016, track by_src, ip 172.18.0.8
suppress gen_id 1, sig_id 1000016, track by_src, ip 172.18.0.19
