# Wazuh - Internal options
# DO NOT CHANGE THIS FILE. Use local_internal_options.conf instead.

analysisd.state_interval=5
analysisd.all_agents_limit=1
analysisd.label_cache_maxage=10
analysisd.show_hidden_labels=0
monitord.rotate_log=1
monitord.size_rotate=512
monitord.day_wait=10
monitord.compress=1
monitord.sign=1
monitord.keep_log_days=31
monitord.skiplist=0
remoted.request_rto_sec=1
remoted.request_rto_msec=0
remoted.max_attempts=4
remoted.sender_pool=8
remoted.recv_counter_flush=128
remoted.comp_average_printout=19999
remoted.verify_msg_id=0
remoted.store_msgs=0
remoted.allow_higher_versions=no
wazuh_modules.task_nice=10
wazuh_modules.max_eps=100
wazuh_modules.kill_timeout=10
wazuh_modules.debug=0
wazuh_database.interval=10
wazuh_database.max_rows_syscheck=0
wazuh_database.max_rows_netaddr=0
wazuh_database.max_rows_netinfo=0
wazuh_database.max_rows_procinfo=0
wazuh_database.max_rows_port=0
wazuh_database.max_rows_hwinfo=0
wazuh_database.max_rows_osinfo=0
wazuh_database.max_rows_ciscat=0
wazuh_database.sync_file=1
integrator.debug=0
authd.debug=0
authd.timeout_auth=60
authd.pass_min_length=8
authd.min_key_length=1024
csyslogd.debug=0
agentlessd.debug=0
logcollector.loop_timeout=2
logcollector.open_attempts=8
logcollector.vcheck_files=64
logcollector.max_lines=10000
logcollector.max_files=1000
logcollector.sock_fail_time=300
logcollector.debug=0
logcollector.exclude_pattern=0
logcollector.rlimit_nofile=1100
agent.warn_level=7
agent.normal_level=6
agent.tolerance=0
agent.state_interval=5
agent.recv_timeout=60
agent.debug=0
execd.debug=0
execd.request_timeout=60
execd.max_restart_lock=600
syscheck.debug=0
rootcheck.debug=0
syscheckd.max_notes=1024
syscheckd.sleep=1
syscheckd.sleep_after=100
auth.debug=0
auth.timeout_seconds=1
auth.timeout_microseconds=0
wazuh_db.rlimit_nofile=65536
wazuh_db.rlimit_nofile=65536
