server {
    listen 80;

    location / {
        proxy_pass http://kibana:5601;
    }

    location /misp/ {
        proxy_pass https://misp:443/;
    }

    location /opencti/ {
        proxy_pass http://opencti:3000/;
    }
}
