input {
  file {
    path => "/var/ossec/logs/alerts/alerts.json"
    codec => "json"
    type => "wazuh-alerts"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/wazuh-sincedb"
    tags => ["wazuh", "json"]
  }
  beats {
    port => 5044
    tags => ["beats"]
  }
}

filter {
  if [type] == "wazuh-alerts" or "wazuh" in [tags] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      add_field => { "[@metadata][index_prefix]" => "wazuh-alerts-4.x" }
    }
    if [data][srcip] {
      geoip {
        source => "[data][srcip]"
        target => "[data][geoip]"
      }
    }
  }
  if "beats" in [tags] {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "filebeat" }
    }
  }
}

output {
  if [type] == "wazuh-alerts" or "wazuh" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "SOCstack2026!"
      index => "wazuh-alerts-4.x-%{+YYYY.MM.dd}"
      template_overwrite => false
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "elastic"
      password => "SOCstack2026!"
      index => "filebeat-%{+YYYY.MM.dd}"
    }
  }
}
